version: '3.8'

services:
  app:
    build: .
    container_name: hexcarteira-poc
    volumes:
      - .:/home/node/app
    networks:
      - node-network
    tty: true
    ports:
      - "3000:3000"
  
  

  db:

    image: mysql:8.0.30-debian
    command: --innodb-use-native-aio=0
    container_name: hexcarteira-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      -  host_cache_size=0s
   
    networks:
      - node-network
networks:
  node-network:
    driver: bridge


  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #   image: localstack/localstack:0.12.18
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     - DEBUG=${DEBUG-}
  #     - PERSISTENCE=1
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - DISABLE_CORS_CHECKS = 1
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./docker/volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"


  